name: horizon_vert
description: "An app for LBS SEIC Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_28pt-Regular.ttf
        - asset: fonts/Inter_18pt-Italic.ttf
          style: italic
        - asset: fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_28pt-BoldItalic.ttf
          weight: 700
          style: italic
